CREATE TABLE "site_settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"logo_url" text,
	"site_name" text,
	"short_name" text,
	"tagline" text,
	"description" text,
	"phone" text,
	"email" text,
	"address" text,
	"instagram_url" text,
	"youtube_url" text,
	"linkedin_url" text,
	"languages" jsonb,
	"hero_slides" jsonb,
	"stats" jsonb,
	"how_it_works_eyebrow" text,
	"how_it_works_title" text,
	"how_it_works_steps" jsonb,
	"level_test_eyebrow" text,
	"level_test_title" text,
	"level_test_description" text,
	"level_test_ready_title" text,
	"level_test_not_ready_title" text,
	"level_test_logged_in_text" text,
	"level_test_guest_text" text,
	"seo_titles" jsonb,
	"seo_descriptions" jsonb,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
